# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sense_pb2 as sense__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sense_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NumpyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessNestedData = channel.unary_unary(
                '/numpy_processing.NumpyService/ProcessNestedData',
                request_serializer=sense__pb2.NestedDataRequest.SerializeToString,
                response_deserializer=sense__pb2.NumpyDictResponse.FromString,
                _registered_method=True)


class NumpyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessNestedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NumpyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessNestedData': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessNestedData,
                    request_deserializer=sense__pb2.NestedDataRequest.FromString,
                    response_serializer=sense__pb2.NumpyDictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'numpy_processing.NumpyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('numpy_processing.NumpyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NumpyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessNestedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/numpy_processing.NumpyService/ProcessNestedData',
            sense__pb2.NestedDataRequest.SerializeToString,
            sense__pb2.NumpyDictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
