# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sense.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sense.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsense.proto\x12\x10numpy_processing\"\x9c\x01\n\x11NestedDataRequest\x12=\n\x05items\x18\x01 \x03(\x0b\x32..numpy_processing.NestedDataRequest.ItemsEntry\x1aH\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.numpy_processing.DataItem:\x02\x38\x01\"\xa1\x01\n\x11NumpyDictResponse\x12\x41\n\x07results\x18\x01 \x03(\x0b\x32\x30.numpy_processing.NumpyDictResponse.ResultsEntry\x1aI\n\x0cResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.numpy_processing.NDArray:\x02\x38\x01\"c\n\x08\x44\x61taItem\x12+\n\x08lidar_np\x18\x01 \x01(\x0b\x32\x19.numpy_processing.NDArray\x12*\n\x05param\x18\x02 \x01(\x0b\x32\x1b.numpy_processing.ParamData\"\x91\x01\n\tParamData\x12\x37\n\x06values\x18\x01 \x03(\x0b\x32\'.numpy_processing.ParamData.ValuesEntry\x1aK\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.numpy_processing.ParamValue:\x02\x38\x01\"\\\n\nParamValue\x12\x30\n\x0b\x61rray_value\x18\x01 \x01(\x0b\x32\x19.numpy_processing.NDArrayH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x42\x07\n\x05value\"5\n\x07NDArray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t2o\n\x0cNumpyService\x12_\n\x11ProcessNestedData\x12#.numpy_processing.NestedDataRequest\x1a#.numpy_processing.NumpyDictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sense_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NESTEDDATAREQUEST_ITEMSENTRY']._loaded_options = None
  _globals['_NESTEDDATAREQUEST_ITEMSENTRY']._serialized_options = b'8\001'
  _globals['_NUMPYDICTRESPONSE_RESULTSENTRY']._loaded_options = None
  _globals['_NUMPYDICTRESPONSE_RESULTSENTRY']._serialized_options = b'8\001'
  _globals['_PARAMDATA_VALUESENTRY']._loaded_options = None
  _globals['_PARAMDATA_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_NESTEDDATAREQUEST']._serialized_start=34
  _globals['_NESTEDDATAREQUEST']._serialized_end=190
  _globals['_NESTEDDATAREQUEST_ITEMSENTRY']._serialized_start=118
  _globals['_NESTEDDATAREQUEST_ITEMSENTRY']._serialized_end=190
  _globals['_NUMPYDICTRESPONSE']._serialized_start=193
  _globals['_NUMPYDICTRESPONSE']._serialized_end=354
  _globals['_NUMPYDICTRESPONSE_RESULTSENTRY']._serialized_start=281
  _globals['_NUMPYDICTRESPONSE_RESULTSENTRY']._serialized_end=354
  _globals['_DATAITEM']._serialized_start=356
  _globals['_DATAITEM']._serialized_end=455
  _globals['_PARAMDATA']._serialized_start=458
  _globals['_PARAMDATA']._serialized_end=603
  _globals['_PARAMDATA_VALUESENTRY']._serialized_start=528
  _globals['_PARAMDATA_VALUESENTRY']._serialized_end=603
  _globals['_PARAMVALUE']._serialized_start=605
  _globals['_PARAMVALUE']._serialized_end=697
  _globals['_NDARRAY']._serialized_start=699
  _globals['_NDARRAY']._serialized_end=752
  _globals['_NUMPYSERVICE']._serialized_start=754
  _globals['_NUMPYSERVICE']._serialized_end=865
# @@protoc_insertion_point(module_scope)
